// Hidden editor for the room data used directly by world.js (f = floor, o = objects, d = doors).
(()=>{
 const $=id=>document.getElementById(id), panel=$('devtools'),canvas=$('map-preview'),ctx=canvas.getContext('2d');
 const sequence=['d','e','v','m','o','d','e'];let progress=0,selected=null,drag=null,tool='select';
 let paintSize=16,paintPixels=Array(256).fill(null),paintDown=false,paintErase=false;
 const bundledMaps=JSON.parse(JSON.stringify(R)),bundledNpcs=JSON.parse(JSON.stringify(NPCS)),bundledSprites=JSON.parse(JSON.stringify(SPRITES)),bundledShops=JSON.parse(JSON.stringify(SHOPS));
 const bundledEnemies=JSON.parse(JSON.stringify(ENEMIES)),bundledAttacks=JSON.parse(JSON.stringify(ATTACK_PATTERNS));
 function current(){return R[+$('map-select').value||0]||R[0]}
 function persist(){try{localStorage.setItem('wick-project-data',JSON.stringify({version:1,migrations:12,maps:R,enemies:ENEMIES,attacks:ATTACK_PATTERNS,npcs:NPCS,sprites:SPRITES,shops:SHOPS}))}catch(e){status('Could not save locally: '+e.message)}}
 function status(s){$('map-status').textContent=s||'Saved locally. Export project data for a backup.'}
 function loadSaved(){try{
  const d=JSON.parse(localStorage.getItem('wick-project-data')||'null');if(!d)return;
  const savedMaps=Array.isArray(d.maps)?d.maps:[];
  if((d.migrations||0)<1){
   const garden=bundledMaps.find(m=>m.id==='lantern-garden'),corridorSeed=bundledMaps.find(m=>m.id==='wax-corridor');
   let gardenIndex=savedMaps.findIndex(m=>m.id==='lantern-garden');
   if(garden&&gardenIndex<0){gardenIndex=savedMaps.length;savedMaps.push(JSON.parse(JSON.stringify(garden)))}
   const corridor=savedMaps.find(m=>m.id==='wax-corridor'),route=corridorSeed?.d?.find(door=>bundledMaps[door.to]?.id==='lantern-garden');
   if(corridor&&route&&gardenIndex>=0){corridor.d=corridor.d||[];const link=corridor.d.find(door=>door.x===route.x&&door.y===route.y&&door.w===route.w&&door.h===route.h);if(link)link.to=gardenIndex;else corridor.d.push({...route,to:gardenIndex})}
   for(const npc of bundledNpcs)if(!d.npcs?.some(n=>n.id===npc.id))d.npcs=(d.npcs||[]).concat([npc]);
   for(const sprite of bundledSprites)if(!d.sprites?.some(s=>s.id===sprite.id))d.sprites=(d.sprites||[]).concat([sprite]);
  }
  const needsUpdate=(d.migrations||0)<2;
  if(needsUpdate){for(const def of bundledNpcs){const saved=d.npcs?.find(n=>n.id===def.id);if(saved&&def.options?.length&&!saved.options)saved.options=JSON.parse(JSON.stringify(def.options))}for(const shop of bundledShops)if(!d.shops?.some(s=>s.id===shop.id))d.shops=(d.shops||[]).concat([shop])}
  const contentUpdate=(d.migrations||0)<8,attackStyleUpdate=(d.migrations||0)<9,mapLayoutUpdate=(d.migrations||0)<10,spawnPointUpdate=(d.migrations||0)<11,encounterRateUpdate=(d.migrations||0)<12;
  if(contentUpdate){
   d.enemies=mergeMissing(d.enemies,bundledEnemies,'id');for(const enemy of d.enemies)if(typeof enemy.natural!=='boolean')enemy.natural=false;d.attacks=mergeMissing(d.attacks,bundledAttacks,'id');
   d.npcs=mergeMissing(d.npcs,bundledNpcs,'id');d.sprites=mergeMissing(d.sprites,bundledSprites,'id');d.shops=mergeMissing(d.shops,bundledShops,'id');
   const regionSeeds=bundledMaps.filter(m=>m.id==='hollow-hall'||m.id==='wax-corridor'||m.id==='dark-room'||m.id==='lantern-garden'||m.id==='last-save-archive'||m.id.startsWith('repo-'));
   for(const seed of regionSeeds){
    let room=savedMaps.find(m=>m.id===seed.id);
    if(!room){room=JSON.parse(JSON.stringify(seed));savedMaps.push(room)}
    else{
     room.f=JSON.parse(JSON.stringify(seed.f));
     room.c=JSON.parse(JSON.stringify(seed.c||[]));
     if(!room.soundData)room.soundData=seed.soundData;
     if(!room.encounters)room.encounters=JSON.parse(JSON.stringify(seed.encounters||[]));
     else room.encounters=[...new Set([...room.encounters,...(seed.encounters||[])])];
     if(!room.encounterSpacing)room.encounterSpacing=seed.encounterSpacing;
     if(room.encounterChance==null)room.encounterChance=seed.encounterChance;
     if(!room.c?.length&&seed.c?.length)room.c=JSON.parse(JSON.stringify(seed.c));
     if(!room.triggers?.some(t=>t.k==='enemy')&&seed.triggers?.length)room.triggers=JSON.parse(JSON.stringify(seed.triggers));
     if(seed.id==='last-save-archive')for(const trigger of room.triggers||[])if(trigger.enemyId==='index-hound')trigger.enemyId='the-archivist';
    }
    room.d=room.d||[];
    room.o=room.o||[];for(const object of seed.o||[])if((object.npcId?.startsWith('repo-story-')||object.repoScene)&&!room.o.some(o=>object.repoScene?o.repoScene===object.repoScene:o.npcId===object.npcId))room.o.push(JSON.parse(JSON.stringify(object)));
    for(const sourceDoor of seed.d||[]){let door=room.d.find(d=>d.targetId===sourceDoor.targetId||(sourceDoor.targetId&&savedMaps[d.to]?.id===sourceDoor.targetId)||(d.x===sourceDoor.x&&d.y===sourceDoor.y&&d.w===sourceDoor.w&&d.h===sourceDoor.h));if(!door){door={...sourceDoor};room.d.push(door)}else Object.assign(door,sourceDoor)}
   }
   const garden=savedMaps.find(m=>m.id==='lantern-garden'),gardenSeed=bundledMaps.find(m=>m.id==='lantern-garden');
   if(garden&&gardenSeed){garden.d=garden.d||[];for(const sourceDoor of gardenSeed.d||[]){if(!sourceDoor.targetId)continue;let door=garden.d.find(d=>d.targetId===sourceDoor.targetId||(d.x===sourceDoor.x&&d.y===sourceDoor.y&&d.w===sourceDoor.w&&d.h===sourceDoor.h));if(!door){door={...sourceDoor};garden.d.push(door)}door.targetId=sourceDoor.targetId}}
   for(const room of savedMaps)for(const door of room.d||[])if(door.targetId){const target=savedMaps.findIndex(m=>m.id===door.targetId);if(target>=0)door.to=target}
  }
  if(attackStyleUpdate){d.attacks=Array.isArray(d.attacks)?d.attacks:[];for(const pattern of bundledAttacks.filter(p=>p.id?.startsWith('repoattack-'))){const i=d.attacks.findIndex(p=>p.id===pattern.id);if(i<0)d.attacks.push(JSON.parse(JSON.stringify(pattern)));else d.attacks[i]=JSON.parse(JSON.stringify(pattern))}}
  if(mapLayoutUpdate){const layoutIds=new Set(['hollow-hall','wax-corridor','dark-room','lantern-garden','last-save-archive',...bundledMaps.filter(m=>m.id.startsWith('repo-')).map(m=>m.id)]);for(const seed of bundledMaps.filter(m=>layoutIds.has(m.id))){let room=savedMaps.find(m=>m.id===seed.id);if(!room){room=JSON.parse(JSON.stringify(seed));savedMaps.push(room);continue}for(const field of ['f','c','d','encounters','encounterSpacing','encounterChance','triggers'])if(seed[field]!==undefined)room[field]=JSON.parse(JSON.stringify(seed[field]));else delete room[field];if(seed.obstacleColor)room.obstacleColor=seed.obstacleColor;else delete room.obstacleColor;room.o=room.o||[];for(const sign of (seed.o||[]).filter(o=>o.k==='sign')){const prior=room.o.find(o=>o.k==='sign'&&o.x===sign.x&&o.y===sign.y);if(prior)Object.assign(prior,JSON.parse(JSON.stringify(sign)));else room.o.push(JSON.parse(JSON.stringify(sign)))}for(const object of seed.o||[])if((object.repoScene||object.npcId?.startsWith('repo-story-'))&&!room.o.some(o=>object.repoScene?o.repoScene===object.repoScene:o.npcId===object.npcId))room.o.push(JSON.parse(JSON.stringify(object)));room.layoutVersion=2}}
  if(mapLayoutUpdate)for(const room of savedMaps)for(const door of room.d||[])if(door.targetId){const target=savedMaps.findIndex(m=>m.id===door.targetId);if(target>=0)door.to=target}
  if(spawnPointUpdate){for(const room of savedMaps)room.spawns=Array.isArray(room.spawns)?room.spawns:[];for(const room of savedMaps)for(let i=0;i<(room.d||[]).length;i++){const door=room.d[i];if(door.targetId){const targetIndex=savedMaps.findIndex(m=>m.id===door.targetId);if(targetIndex>=0)door.to=targetIndex}const target=savedMaps[door.to];if(!target||door.to<0)continue;const id=door.arrivalSpawnId||`entry-${room.id||'room'}-${i+1}`;door.arrivalSpawnId=id;if(!target.spawns.some(p=>String(p.id)===String(id)))target.spawns.push({id,x:Number.isFinite(+door.px)?+door.px:target.f[0]+32,y:Number.isFinite(+door.py)?+door.py:target.f[1]+target.f[3]/2})}}
  if(encounterRateUpdate)for(const room of savedMaps){const seed=bundledMaps.find(m=>m.id===room.id);if(seed&&seed.encounterSpacing!=null&&seed.encounterChance!=null){room.encounterSpacing=seed.encounterSpacing;room.encounterChance=seed.encounterChance}}
  d.migrations=12;replace(R,savedMaps);replace(ENEMIES,d.enemies);replace(ATTACK_PATTERNS,d.attacks);replace(NPCS,d.npcs);replace(SPRITES,d.sprites);replace(SHOPS,d.shops);if(needsUpdate||contentUpdate||attackStyleUpdate||mapLayoutUpdate||spawnPointUpdate||encounterRateUpdate)persist()
 }catch(e){console.warn('WICK data could not be loaded',e)}}
 function mergeMissing(saved,defaults,key){const out=Array.isArray(saved)?saved:[];for(const item of defaults){const found=out.find(x=>x[key]===item[key]);if(!found)out.push(JSON.parse(JSON.stringify(item)));else for(const [field,value] of Object.entries(item))if(found[field]==null)found[field]=JSON.parse(JSON.stringify(value))}return out}
 function replace(dst,src){if(Array.isArray(src)){dst.splice(0,dst.length,...src)}}
 function fillSelect(el,items,first,label){el.innerHTML='';if(first){const o=document.createElement('option');o.value='';o.textContent=first;el.append(o)}for(const [i,x] of items.entries()){const o=document.createElement('option');o.value=String(i);o.textContent=label(x);el.append(o)}}
 function refresh(){const prev=+$('map-select').value||0;fillSelect($('map-select'),R,null,x=>x.n||x.id);$('map-select').value=String(Math.min(prev,R.length-1));fillSelect($('door-target'),R,'Outside / ending',x=>x.n||x.id);fillSelect($('map-enemy'),ENEMIES,'No encounter',x=>x.name+' ('+x.id+')');fillSelect($('map-npc'),NPCS,'Choose NPC',x=>x.name+' ('+x.id+')');fillSelect($('map-sprite'),SPRITES,'Choose sprite',x=>x.id);fillSelect($('enemy-select'),ENEMIES,null,x=>x.name+' ('+x.id+')');syncForm();syncEnemyForm();draw()}
 function syncEnemyForm(){const e=ENEMIES[+$('enemy-select').value||0];if(!e)return;$('enemy-natural').value=String(e.natural===true);$('enemy-data').textContent=JSON.stringify(e,null,2)}
 function syncForm(){const r=current();if(!r)return;$('map-name').value=r.n||'';['fx','fy','fw','fh'].forEach((v,i)=>$("map-"+v).value=r.f[i]);$('map-bg').value=/^#[0-9a-f]{6}$/i.test(r.bg||'')?r.bg:'#1b1426';const ei=ENEMIES.findIndex(e=>e.id===r.enemyId);$('map-enemy').value=ei<0?'':String(ei);draw()}
 function xy(e){const b=canvas.getBoundingClientRect();return{x:(e.clientX-b.left)*640/b.width,y:(e.clientY-b.top)*480/b.height}}
 function draw(){if(!ctx)return;const r=current();ctx.clearRect(0,0,640,480);ctx.fillStyle='#07070a';ctx.fillRect(0,0,640,480);if(!r)return;const [x,y,w,h]=r.f;ctx.fillStyle=r.bg||'#181820';ctx.fillRect(x,y,w,h);ctx.strokeStyle='#9482ba';ctx.lineWidth=3;ctx.strokeRect(x,y,w,h);
  for(let gx=Math.ceil(x/32)*32;gx<x+w;gx+=32){ctx.strokeStyle='rgba(255,255,255,.08)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(gx,y);ctx.lineTo(gx,y+h);ctx.stroke()}for(let gy=Math.ceil(y/32)*32;gy<y+h;gy+=32){ctx.beginPath();ctx.moveTo(x,gy);ctx.lineTo(x+w,gy);ctx.stroke()}
  (r.c||[]).forEach((d,i)=>drawRect(d,'rgba(255,55,55,.22)','#ff6565','Collision '+(i+1),'collision',i));
  (r.triggers||[]).forEach((d,i)=>drawRect(d,d.k==='enemy'?'rgba(255,140,30,.28)':'rgba(60,210,255,.2)',d.k==='enemy'?'#ff9b38':'#55d9ff',(d.k==='enemy'?'Enemy':'Dialogue')+' trigger '+(i+1),'trigger',i));
  (r.d||[]).forEach((d,i)=>drawRect(d,'rgba(255,210,122,.35)','#ffd27a','Door '+(d.id||i+1)+' → '+(d.arrivalSpawnId||'spawn?'),'door',i));
  (r.spawns||[]).forEach(p=>{ctx.fillStyle='#55d9ff';ctx.beginPath();ctx.arc(p.x,p.y,6,0,Math.PI*2);ctx.fill();ctx.fillStyle='#fff';ctx.font='10px sans-serif';ctx.fillText('Spawn: '+p.id,p.x+8,p.y-7)});
  (r.o||[]).forEach((o,i)=>{const rad=o.k==='sign'?12:o.k==='npc'||o.k==='sprite'?12:9,sprite=SPRITES.find(s=>s.id===(o.spriteId||(o.k==='sprite'?o.spriteId:NPCS.find(n=>n.id===o.npcId)?.spriteId)));if(sprite?.pixels){const scale=1.3;for(let p=0;p<sprite.pixels.length;p++)if(sprite.pixels[p]){ctx.fillStyle=sprite.pixels[p];ctx.fillRect(o.x-sprite.width*scale/2+(p%sprite.width)*scale,o.y-sprite.height*scale+Math.floor(p/sprite.width)*scale,scale,scale)}}else{ctx.fillStyle=({sign:'#a87946',npc:'#9b82e8',save:'#ffe066',chest:'#ab7527',wickmob:'#fa8739',wick:'#e6dec5'})[o.k]||'#aaa';ctx.fillRect(o.x-rad,o.y-rad,rad*2,rad*2)}ctx.fillStyle='#fff';ctx.font='9px sans-serif';ctx.fillText(o.k==='sprite'?'sprite:'+o.spriteId:o.k,o.x-rad,o.y-rad-3);if(selected?.kind==='object'&&selected.i===i){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(o.x-rad-2,o.y-rad-2,rad*2+4,rad*2+4)}});
  if(selected?.kind==='floor')handle(x+w,y+h);
  ctx.fillStyle='#d7d7dc';ctx.font='12px sans-serif';ctx.fillText(r.n||r.id,12,18);ctx.fillStyle='#aaa';ctx.fillText('Select and drag · blue handles resize floor and area rectangles',12,466)}
 function handle(x,y){ctx.fillStyle='#55d9ff';ctx.fillRect(x-5,y-5,10,10);ctx.strokeStyle='#06131a';ctx.strokeRect(x-5,y-5,10,10)}
 function drawRect(d,fill,stroke,label,kind,i){ctx.fillStyle=fill;ctx.fillRect(d.x,d.y,d.w,d.h);ctx.strokeStyle=stroke;ctx.lineWidth=2;ctx.strokeRect(d.x,d.y,d.w,d.h);ctx.fillStyle='#fff';ctx.font='10px sans-serif';ctx.fillText(label,d.x+2,d.y+12);if(selected?.kind===kind&&selected.i===i)handle(d.x+d.w,d.y+d.h)}
 function centerDistance(p,x,y){return Math.hypot(p.x-x,p.y-y)}
 function hitTest(p){const r=current(),[x,y,w,h]=r.f;const rectHit=(list,kind)=>{for(let i=(list||[]).length-1;i>=0;i--){const d=list[i];if(p.x>d.x+d.w-12&&p.y>d.y+d.h-12&&p.x<d.x+d.w+8&&p.y<d.y+d.h+8)return{kind,i,resize:true};if(p.x>=d.x-5&&p.x<=d.x+d.w+5&&p.y>=d.y-5&&p.y<=d.y+d.h+5)return{kind,i}}return null};if(selected?.kind==='floor'&&p.x>x+w-13&&p.y>y+h-13)return{kind:'floor',resize:true};let q=rectHit(r.triggers,'trigger')||rectHit(r.c,'collision')||rectHit(r.d,'door');if(q)return q;
  for(let i=(r.spawns||[]).length-1;i>=0;i--){const s=r.spawns[i];if(centerDistance(p,s.x,s.y)<10)return{kind:'spawn',i}}
  for(let i=(r.o||[]).length-1;i>=0;i--){const o=r.o[i];if(centerDistance(p,o.x,o.y)<18)return{kind:'object',i}}
  if(p.x>=x-6&&p.x<=x+w+6&&p.y>=y-6&&p.y<=y+h+6)return{kind:'floor',resize:p.x>x+w-14&&p.y>y+h-14};return null}
 function pointerDown(e){const p=xy(e),r=current();tool=$('map-tool').value;if(tool==='select'){selected=hitTest(p);const arr=selected?.kind==='door'?r.d:selected?.kind==='trigger'?r.triggers:selected?.kind==='collision'?r.c:selected?.kind==='spawn'?r.spawns:null;if(selected?.kind==='door'){$('door-spawn-id').value=r.d[selected.i]?.arrivalSpawnId||'';$('door-target').value=r.d[selected.i]?.to>=0?String(r.d[selected.i].to):''}drag=selected?{...selected,start:p,origin:selected.kind==='floor'?r.f.slice():arr?{...arr[selected.i]}:{...r.o[selected.i]}}:null;draw();return}
  if(tool==='erase'){for(let i=(r.spawns||[]).length-1;i>=0;i--)if(centerDistance(p,r.spawns[i].x,r.spawns[i].y)<10){const id=r.spawns[i].id;r.spawns.splice(i,1);for(const room of R)for(const door of room.d||[])if(R[door.to]===r&&String(door.arrivalSpawnId)===String(id))door.arrivalSpawnId='';persist();draw();status('Spawn point erased.');return}for(let i=(r.o||[]).length-1;i>=0;i--)if(centerDistance(p,r.o[i].x,r.o[i].y)<18){r.o.splice(i,1);persist();draw();status('Object erased.');return}for(const [list,key] of [[r.d,'door'],[r.c,'collision'],[r.triggers,'trigger']])for(let i=(list||[]).length-1;i>=0;i--){let d=list[i];if(p.x>=d.x&&p.x<=d.x+d.w&&p.y>=d.y&&p.y<=d.y+d.h){list.splice(i,1);persist();draw();status(key+' area erased.');return}}status('Nothing to erase here.');return}
  if(tool==='spawn'){r.spawns=r.spawns||[];const id=$('spawn-id').value.trim()||'spawn-'+(r.spawns.length+1);if(r.spawns.some(s=>String(s.id)===id)){status('That spawn point ID already exists in this room.');return}r.spawns.push({id,x:Math.round(p.x),y:Math.round(p.y)});persist();draw();status('Spawn point '+id+' added.');return}
  if(tool==='door'){r.d=r.d||[];const targetValue=$('door-target').value,targetIndex=targetValue===''?-1:+targetValue;r.d.push({x:Math.round(p.x),y:Math.round(p.y),w:32,h:64,to:targetIndex,targetId:targetIndex>=0?R[targetIndex]?.id:undefined,px:+$('door-px').value||100,py:+$('door-py').value||250,arrivalSpawnId:$('door-spawn-id').value.trim()||undefined});selected={kind:'door',i:r.d.length-1};persist();draw();status('Door added. Set its destination room and the spawn point ID inside that room.');return}
  if(tool==='collision'||tool==='enemy-trigger'||tool==='dialogue-trigger'){if(tool==='collision'){r.c=r.c||[];r.c.push({x:Math.round(p.x),y:Math.round(p.y),w:64,h:48});selected={kind:'collision',i:r.c.length-1}}else{r.triggers=r.triggers||[];const trigger={k:tool==='enemy-trigger'?'enemy':'dialogue',x:Math.round(p.x),y:Math.round(p.y),w:64,h:48};if(trigger.k==='enemy')trigger.enemyId=r.enemyId||ENEMIES[0]?.id;else trigger.t=lines($('map-object-text').value||'* ...');r.triggers.push(trigger);selected={kind:'trigger',i:r.triggers.length-1}}persist();draw();status('Area added. Drag or resize it in Select mode.');return}
  const k=tool;if(k==='sprite'&&!SPRITES[+$('map-sprite').value]){status('Create or select a pixel sprite first.');return}if((k==='sign'||k==='npc'||k==='wickmob'||k==='sprite')&&(r.o||[]).some(o=>o.k===k&&Math.hypot(o.x-p.x,o.y-p.y)<24)){status('There is already a '+k+' here. Select it or erase it first.');return}
  if(k==='sprite'){r.o.push({k:'sprite',spriteId:SPRITES[+$('map-sprite').value].id,x:Math.round(p.x),y:Math.round(p.y)});selected={kind:'object',i:r.o.length-1};persist();draw();status('Sprite instance placed.');return}
  let o={k,x:Math.round(p.x),y:Math.round(p.y)};if(k==='sign')o.t=lines($('map-object-text').value||'* A sign.');if(k==='npc'){const n=NPCS[+$('map-npc').value];if(n){o.npcId=n.id;o.t=n.dialogue||['* '+n.name+'.']}}if(k==='chest'){o.id='chest-'+Date.now();o.t=lines($('map-object-text').value||'* You found something.')};r.o.push(o);selected={kind:'object',i:r.o.length-1};persist();draw();status(k+' added.');}
 function lines(s){return s.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)}
 function pointerMove(e){if(!drag)return;const p=xy(e),r=current(),dx=p.x-drag.start.x,dy=p.y-drag.start.y;if(drag.kind==='floor'){const f=r.f;if(drag.resize){f[2]=Math.max(32,Math.round(drag.origin[2]+dx));f[3]=Math.max(32,Math.round(drag.origin[3]+dy))}else{f[0]=Math.max(0,Math.min(640-f[2],Math.round(drag.origin[0]+dx)));f[1]=Math.max(0,Math.min(480-f[3],Math.round(drag.origin[1]+dy)))}syncFields()}
  else {const list=drag.kind==='door'?r.d:drag.kind==='trigger'?r.triggers:drag.kind==='collision'?r.c:drag.kind==='spawn'?r.spawns:null;if(list){const d=list[drag.i],o=drag.origin;if(drag.resize){d.w=Math.max(10,Math.round(o.w+dx));d.h=Math.max(10,Math.round(o.h+dy))}else{d.x=Math.round(o.x+dx);d.y=Math.round(o.y+dy)}}else if(drag.kind==='object'){const o=r.o[drag.i];o.x=Math.round(drag.origin.x+dx);o.y=Math.round(drag.origin.y+dy)}}draw()}
 function pointerUp(){if(drag){persist();status('Room geometry saved.');drag=null}}
 function syncFields(){const f=current().f;['fx','fy','fw','fh'].forEach((v,i)=>$("map-"+v).value=f[i])}
 function updateField(id,fn){$(id).addEventListener('change',()=>{fn(current());persist();draw()})}
 function drawSpriteCanvas(){const c=$('sprite-canvas'),q=c.getContext('2d'),cell=c.width/paintSize;q.clearRect(0,0,c.width,c.height);q.fillStyle='#101116';q.fillRect(0,0,c.width,c.height);for(let i=0;i<paintPixels.length;i++)if(paintPixels[i]){q.fillStyle=paintPixels[i];q.fillRect(i%paintSize*cell,Math.floor(i/paintSize)*cell,cell,cell)}q.strokeStyle='rgba(255,255,255,.18)';q.lineWidth=1;for(let i=0;i<=paintSize;i++){q.beginPath();q.moveTo(i*cell,0);q.lineTo(i*cell,c.height);q.stroke();q.beginPath();q.moveTo(0,i*cell);q.lineTo(c.width,i*cell);q.stroke()}}
 function paintSprite(e){if(!paintDown)return;const c=$('sprite-canvas'),b=c.getBoundingClientRect(),cell=c.width/paintSize,x=Math.floor((e.clientX-b.left)*c.width/b.width/cell),y=Math.floor((e.clientY-b.top)*c.height/b.height/cell);if(x<0||y<0||x>=paintSize||y>=paintSize)return;paintPixels[y*paintSize+x]=paintErase?null:$('sprite-color').value;drawSpriteCanvas()}
 function saveSpriteAndNpc(){const base=($('sprite-name').value||'new-sprite').toLowerCase().trim().replace(/[^a-z0-9_-]+/g,'-'),id=base||'new-sprite',size=paintSize,sprite={id,width:size,height:size,pixels:paintPixels.slice()};const si=SPRITES.findIndex(s=>s.id===id);if(si<0)SPRITES.push(sprite);else SPRITES[si]=sprite;const npcName=$('npc-name').value.trim(),npcId=npcName.toLowerCase().replace(/[^a-z0-9_-]+/g,'-');if(npcName){const n={id:npcId||id,name:npcName,spriteId:id,dialogue:lines($('npc-dialogue').value)};const ni=NPCS.findIndex(x=>x.id===n.id);if(ni<0)NPCS.push(n);else NPCS[ni]=n}fillSelect($('map-sprite'),SPRITES,'Choose sprite',x=>x.id);fillSelect($('map-npc'),NPCS,'Choose NPC',x=>x.name+' ('+x.id+')');$('map-sprite').value=String(SPRITES.findIndex(s=>s.id===id));persist();drawSpriteCanvas();status('Sprite saved. Choose “Sprite instance” to place it, or choose the NPC in the NPC tool.');$('sprite-data').textContent=JSON.stringify(sprite,null,2)}
 const repoCategories={
  'Monsters':()=>Object.entries(REPO_SOURCE_CONTENT.monsters.monsters).map(([key,value])=>[key,{...value,name:key,wick:ENEMIES.find(e=>e.repoKey===key)}]),
  'Boss phase data':()=>Object.entries(REPO_SOURCE_CONTENT.monsters.BOSS_PHASE_TWO),
  'Enemy dialogue':()=>Object.entries(REPO_SOURCE_CONTENT.monsters.ENEMY_DIALOGUE),
  'Items and equipment':()=>Object.entries(REPO_SOURCE_CONTENT.items.ITEMS),
  'Skills':()=>Object.entries(REPO_SOURCE_CONTENT.items.SKILLS),
  'Crafting recipes':()=>Object.entries(REPO_SOURCE_CONTENT.items.recipes),
  'Shop prices':()=>Object.entries({buy:REPO_SOURCE_CONTENT.items.SHOP_BUY,sell:REPO_SOURCE_CONTENT.items.SHOP_SELL}),
  'Spells and perks':()=>Object.entries({...REPO_SOURCE_CONTENT.rpgSystems.SPELLS,...REPO_SOURCE_CONTENT.rpgSystems.PERKS}),
  'Main quests':()=>Object.entries(REPO_SOURCE_CONTENT.dialogue.STORY_QUESTS),
  'Side quests':()=>Object.entries(REPO_SOURCE_CONTENT.rpgSystems.SIDE_QUESTS),
  'Story chapters':()=>REPO_SOURCE_CONTENT.dialogue.STORY_CHAPTERS.map(x=>[x.title,x]),
  'Story scenes and dialogue':()=>Object.entries(REPO_SOURCE_CONTENT.dialogue.STORY_SCENES),
  'Combat scenes':()=>Object.entries(REPO_SOURCE_CONTENT.scenes.GAME_SCENES),
  'Companions':()=>Object.entries(REPO_SOURCE_CONTENT.rpgSystems.COMPANION_DEFS),
  'Companion quests and dialogue':()=>Object.entries({hunts:REPO_SOURCE_CONTENT.rpgSystems.COMPANION_PERSONAL_QUESTS,bondLines:REPO_SOURCE_CONTENT.rpgSystems.COMPANION_BOND_LINES,replayLines:REPO_SOURCE_CONTENT.dialogue.COMPANION_REPLAY_LINES}),
  'Regions and keepsakes':()=>Object.entries({areas:REPO_SOURCE_CONTENT.dialogue.STORY_AREAS,keepsakes:REPO_SOURCE_CONTENT.rpgSystems.REGION_KEEPSAKES}),
  'Factions and towns':()=>Object.entries({factions:REPO_SOURCE_CONTENT.rpgSystems.FACTIONS,towns:REPO_SOURCE_CONTENT.rpgSystems.TOWNS}),
  'Achievements and endings':()=>Object.entries({achievements:REPO_SOURCE_CONTENT.rpgSystems.ACHIEVEMENTS,rewards:REPO_SOURCE_CONTENT.rpgSystems.ACHIEVEMENT_REWARDS,endings:REPO_SOURCE_CONTENT.dialogue.ENDINGS}),
  'Soundtrack files':()=>REPO_SOURCE_AUDIO.map(x=>[x,{path:x}])
 };
 function repoEntries(){return repoCategories[$('repo-category').value]?.()||[]}
 function renderRepoEntry(){const entries=repoEntries(),i=+$('repo-entry').value||0,entry=entries[i];$('repo-count').textContent=entries.length+' entries in this group';$('repo-detail').textContent=entry?JSON.stringify(entry[1],null,2):'No entries.';$('repo-test-enemy').disabled=$('repo-category').value!=='Monsters'||!entry}
 function fillRepo(){const category=$('repo-category'),entry=$('repo-entry'),oldCategory=category.value;category.innerHTML='';Object.keys(repoCategories).forEach(name=>{const o=document.createElement('option');o.value=name;o.textContent=name;category.append(o)});category.value=repoCategories[oldCategory]?oldCategory:'Monsters';const items=repoEntries();entry.innerHTML='';items.forEach(([name],i)=>{const o=document.createElement('option');o.value=String(i);o.textContent=name;entry.append(o)});renderRepoEntry()}
 function launchTest(enemyId,patternId){const enemy=ENEMIES.find(e=>e.id===enemyId);if(!enemy)return;panel.classList.remove('visible');startDevBattleTest(enemyId,patternId)}
 function init(){loadSaved();refresh();fillRepo();$('repo-category').onchange=fillRepo;$('repo-entry').onchange=renderRepoEntry;$('repo-test-enemy').onclick=()=>{const item=repoEntries()[+$('repo-entry').value||0],enemy=item&&ENEMIES.find(e=>e.repoKey===item[0]);if(enemy)launchTest(enemy.id)};
  $('enemy-test').onclick=()=>launchTest(ENEMIES[+$('enemy-select').value||0]?.id);$('attack-test').onclick=()=>launchTest(ENEMIES[0]?.id,ATTACK_PATTERNS[+$('attack-select').value||0]?.id);
  canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);addEventListener('pointerup',pointerUp);
  const sc=$('sprite-canvas');paintSize=+$('sprite-size').value||16;paintPixels=Array(paintSize*paintSize).fill(null);drawSpriteCanvas();sc.addEventListener('pointerdown',e=>{paintDown=true;paintSprite(e)});sc.addEventListener('pointermove',paintSprite);addEventListener('pointerup',()=>paintDown=false);$('sprite-size').onchange=()=>{paintSize=+$('sprite-size').value;paintPixels=Array(paintSize*paintSize).fill(null);drawSpriteCanvas()};$('sprite-color').oninput=()=>paintErase=false;$('sprite-erase').onclick=()=>paintErase=true;$('sprite-clear').onclick=()=>{paintPixels.fill(null);drawSpriteCanvas()};$('sprite-save').onclick=saveSpriteAndNpc;
  $('map-select').onchange=()=>{selected=null;syncForm()};$('map-tool').onchange=()=>{selected=null;draw()};
  $('enemy-select').onchange=syncEnemyForm;$('enemy-natural').onchange=()=>{const e=ENEMIES[+$('enemy-select').value||0];if(e){e.natural=$('enemy-natural').value==='true';persist();syncEnemyForm();status(e.name+(e.natural?' can appear in natural encounters.':' will only appear in placed encounters.'))}};
  updateField('map-name',r=>r.n=$('map-name').value);['fx','fy','fw','fh'].forEach((v,i)=>updateField('map-'+v,r=>r.f[i]=+$("map-"+v).value));updateField('map-bg',r=>r.bg=$('map-bg').value);updateField('map-enemy',r=>r.enemyId=ENEMIES[+$('map-enemy').value]?.id||null);
  $('map-new').onclick=()=>{const id='room-'+Date.now();R.push({id,n:'NEW ROOM',f:[120,120,400,240],bg:'#1b1426',o:[],d:[]});refresh();$('map-select').value=String(R.length-1);syncForm();persist()};$('map-delete').onclick=()=>{if(R.length<2){status('Keep at least one room.');return}const i=+$('map-select').value;R.splice(i,1);R.forEach(r=>(r.d||[]).forEach(d=>{if(d.to===i)d.to=-1;else if(d.to>i)d.to--}));selected=null;refresh();persist();status('Room deleted.')};
  $('door-target').onchange=()=>{if(selected?.kind!=='door')return;const value=$('door-target').value,door=current().d[selected.i];if(door){door.to=value===''?-1:+value;door.targetId=door.to>=0?R[door.to]?.id:undefined;persist();draw();status('Door destination room updated.')}};$('door-spawn-id').onchange=()=>{if(selected?.kind!=='door')return;const door=current().d[selected.i];if(door){door.arrivalSpawnId=$('door-spawn-id').value.trim();persist();draw();status('Door arrival spawn point updated.')}};$('map-background').onchange=e=>readFile(e,'backgroundData');$('map-sound').onchange=e=>readFile(e,'soundData');
  document.querySelectorAll('[data-devtab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.devtab').forEach(x=>x.classList.remove('active'));$('dev-'+b.dataset.devtab).classList.add('active')});$('dev-close').onclick=()=>panel.classList.remove('visible');
  $('project-export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,maps:R,enemies:ENEMIES,attacks:ATTACK_PATTERNS,npcs:NPCS,sprites:SPRITES,shops:SHOPS},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='wick-project.json';a.click();URL.revokeObjectURL(a.href)};
  $('project-import').onchange=async e=>{try{const d=JSON.parse(await e.target.files[0].text());replace(R,d.maps);replace(ENEMIES,d.enemies);replace(ATTACK_PATTERNS,d.attacks);replace(NPCS,d.npcs);replace(SPRITES,d.sprites);replace(SHOPS,d.shops);refresh();persist();status('Project data imported.')}catch(err){status('Import failed: '+err.message)}};
  addEventListener('keydown',e=>{const key=e.key.toLowerCase();if(key===sequence[progress])progress++;else progress=key===sequence[0]?1:0;if(progress===sequence.length){panel.classList.add('visible');progress=0;e.preventDefault()}if(panel.classList.contains('visible')){if(key==='escape')panel.classList.remove('visible');e.stopImmediatePropagation()}},true);
 }
 function readFile(e,key){const f=e.target.files[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{current()[key]=reader.result;persist();draw();status(f.name+' attached to this room.')}}
 init();
})();
